# Generated by Django 4.2.10 on 2024-12-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("puesto", models.CharField(max_length=250)),
                ("empresa", models.CharField(max_length=250)),
                ("descripcion", models.TextField()),
                ("inicio", models.DateField()),
                ("fin", models.DateField()),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="experiencia_fotos/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=230)),
                ("descripcion", models.TextField()),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="logros/"),
                ),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="logros_imagenes/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("descripcion", models.TextField()),
                ("fecha", models.DateField()),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="proyectos/"),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="proyectos_videos/"
                    ),
                ),
            ],
        ),
    ]
